com.ucoruh.password.PasswordGenerator Class Reference
Utility class for generating random passwords.
Classes
class HuffmanNode
Huffman Tree Node for encoding/decoding.
Static Public Member Functions
static String generatePassword (int length)
Generates a random password of a given length.
static String generatePassword (int length, boolean includeUppercase, boolean includeLowercase, boolean includeDigits, boolean includeSpecial)
Generates a random password with specific character sets.
static void generate (Scanner scanner)
Prompts user for password length and generates a password.
static int kmpSearch (String text, String pattern)
Searches for pattern in text using KMP algorithm.
static boolean containsPattern (String password, String pattern)
Checks if a password contains a specific pattern.
static boolean isWeakPattern (String password)
Checks if a password contains weak patterns.
static String generateStrongPassword (int length)
Generates a strong password that doesn't contain weak patterns.
static HuffmanNode buildHuffmanTree (Map< Character, Integer > frequencies)
Builds Huffman tree from character frequencies.
static Map< Character, String > generateHuffmanCodes (HuffmanNode root)
Generates Huffman codes for all characters.
static String compressPassword (String password)
Compresses password using Huffman coding.
static String decompressPassword (String compressed, HuffmanNode root)
Decompresses password using Huffman tree.
static double getCompressionRatio (String original, String compressed)
Calculates compression ratio.
Detailed Description
Utility class for generating random passwords.
Author
Password Manager Team
Version
1.0
This class provides methods to generate secure random passwords using configurable character sets.
Definition at line 18 of file PasswordGenerator.java.
Member Function Documentation
buildHuffmanTree()
static HuffmanNode com.ucoruh.password.PasswordGenerator.buildHuffmanTree (Map< Character, Integer > frequencies) [static]
Builds Huffman tree from character frequencies.
Uses a priority queue to build optimal encoding tree.
Parameters
frequencies Map of character frequencies
Returns
Root of Huffman tree
Definition at line 381 of file PasswordGenerator.java.
                                                                                  {
    if (frequencies == null || frequencies.isEmpty()) {
      return null;
    }
    PriorityQueue<HuffmanNode> pq = new PriorityQueue<>();
    // Create leaf nodes for each character
    for (Map.Entry<Character, Integer> entry : frequencies.entrySet()) {
      pq.offer(new HuffmanNode(entry.getKey(), entry.getValue()));
    }
    // Build tree by combining nodes
    while (pq.size() > 1) {
      HuffmanNode left = pq.poll();
      HuffmanNode right = pq.poll();
      HuffmanNode parent = new HuffmanNode(
        left.frequency + right.frequency, left, right
      );
      pq.offer(parent);
    }
    return pq.poll();
  }
Referenced by com.ucoruh.password.PasswordGenerator.compressPassword().
compressPassword()
static String com.ucoruh.password.PasswordGenerator.compressPassword (String password) [static]
Compresses password using Huffman coding.
Returns binary string representation of compressed password.
Parameters
password Password to compress
Returns
Compressed password as binary string, or empty if input is invalid
Definition at line 452 of file PasswordGenerator.java.
                                                         {
    if (password == null || password.isEmpty()) {
      return "";
    }
    // Calculate character frequencies
    Map<Character, Integer> frequencies = new HashMap<>();
    for (char c : password.toCharArray()) {
      frequencies.put(c, frequencies.getOrDefault(c, 0) + 1);
    }
    // Build Huffman tree
    HuffmanNode root = buildHuffmanTree(frequencies);
    if (root == null) {
      return "";
    }
    // Generate codes
    Map<Character, String> codes = generateHuffmanCodes(root);
    // Encode password
    StringBuilder compressed = new StringBuilder();
    for (char c : password.toCharArray()) {
      compressed.append(codes.get(c));
    }
    return compressed.toString();
  }
References com.ucoruh.password.PasswordGenerator.buildHuffmanTree(), and com.ucoruh.password.PasswordGenerator.generateHuffmanCodes().
containsPattern()
static boolean com.ucoruh.password.PasswordGenerator.containsPattern (String password, String pattern) [static]
Checks if a password contains a specific pattern.
Parameters
password The password to check
pattern The pattern to search for
Returns
boolean true if pattern is found, false otherwise
Definition at line 249 of file PasswordGenerator.java.
                                                                         {
    return kmpSearch(password, pattern) != -1;
  }
References com.ucoruh.password.PasswordGenerator.kmpSearch().
Referenced by com.ucoruh.password.PasswordGenerator.isWeakPattern().
decompressPassword()
static String com.ucoruh.password.PasswordGenerator.decompressPassword (String compressed, HuffmanNode root) [static]
Decompresses password using Huffman tree.
Traverses tree using binary string to decode original password.
Parameters
compressed Compressed binary string
root Root of Huffman tree
Returns
Decompressed password, or empty if input is invalid
Definition at line 491 of file PasswordGenerator.java.
                                                                               {
    if (compressed == null || compressed.isEmpty() || root == null) {
      return "";
    }
    StringBuilder decompressed = new StringBuilder();
    // Special case: single character tree (root is a leaf)
    if (root.isLeaf()) {
      // Each bit represents one occurrence of the character
      for (int i = 0; i < compressed.length(); i++) {
        decompressed.append(root.character);
      }
      return decompressed.toString();
    }
    HuffmanNode current = root;
    for (char bit : compressed.toCharArray()) {
      if (bit == '0') {
        current = current.left;
      } else if (bit == '1') {
        current = current.right;
      }
      if (current != null && current.isLeaf()) {
        decompressed.append(current.character);
        current = root;
      }
    }
    return decompressed.toString();
  }
generate()
static void com.ucoruh.password.PasswordGenerator.generate (Scanner scanner) [static]
Prompts user for password length and generates a password.
This method reads the desired password length from the user input using the provided Scanner, then generates and prints the random password.
Parameters
scanner Scanner object for reading user input
Definition at line 145 of file PasswordGenerator.java.
                                               {
    System.out.print("Enter desired password length: ");
    try {
      int length = Integer.parseInt(scanner.nextLine());
      String newPassword = generatePassword(length);
      System.out.println("Generated Password: " + newPassword);
    } catch (NumberFormatException e) {
      System.out.println("Invalid input. Please enter a valid number.");
    }
  }
References com.ucoruh.password.PasswordGenerator.generatePassword().
generateHuffmanCodes()
static Map< Character, String > com.ucoruh.password.PasswordGenerator.generateHuffmanCodes (HuffmanNode root) [static]
Generates Huffman codes for all characters.
Parameters
root Root of Huffman tree
Returns
Map of character to Huffman code
Definition at line 435 of file PasswordGenerator.java.
                                                                              {
    Map<Character, String> huffmanCodes = new HashMap<>();
    if (root != null) {
      generateCodesHelper(root, "", huffmanCodes);
    }
    return huffmanCodes;
  }
Referenced by com.ucoruh.password.PasswordGenerator.compressPassword().
generatePassword() [1/2]
static String com.ucoruh.password.PasswordGenerator.generatePassword (int length) [static]
Generates a random password of a given length.
This method uses a random number generator and a predefined character set to create a password string of the specified length. If a negative length is provided, an empty string is returned.
Parameters
length The desired length of the password
Returns
String A randomly generated password
Definition at line 59 of file PasswordGenerator.java.
                                                    {
    // For backward compatibility, use all character sets
    return generatePassword(length, true, true, true, true);
  }
References com.ucoruh.password.PasswordGenerator.generatePassword().
Referenced by com.ucoruh.password.PasswordGenerator.generate(), com.ucoruh.password.PasswordGenerator.generatePassword(), and com.ucoruh.password.PasswordGenerator.generateStrongPassword().
generatePassword() [2/2]
static String com.ucoruh.password.PasswordGenerator.generatePassword (int length, boolean includeUppercase, boolean includeLowercase, boolean includeDigits, boolean includeSpecial) [static]
Generates a random password with specific character sets.
This method allows selective inclusion of character sets (uppercase letters, lowercase letters, digits, and special characters) in the generated password. At least one character set must be included.
Parameters
length The desired length of the password
includeUppercase Whether to include uppercase letters (A-Z)
includeLowercase Whether to include lowercase letters (a-z)
includeDigits Whether to include digits (0-9)
includeSpecial Whether to include special characters
Returns
String A randomly generated password meeting the specified criteria
Definition at line 77 of file PasswordGenerator.java.
                                                                {
    // Return empty string for zero or negative length
    if (length <= 0) {
      return "";
    }
    // Build the character set based on includes
    StringBuilder charSetBuilder = new StringBuilder();
    if (includeUppercase) charSetBuilder.append(UPPERCASE_CHARS);
    if (includeLowercase) charSetBuilder.append(LOWERCASE_CHARS);
    if (includeDigits) charSetBuilder.append(DIGIT_CHARS);
    if (includeSpecial) charSetBuilder.append(SPECIAL_CHARS);
    // If no character set is selected, use lowercase as default
    String charSet = charSetBuilder.length() > 0 ? charSetBuilder.toString() : LOWERCASE_CHARS;
    // Generate the password
    StringBuilder password = new StringBuilder(length);
    Random random = new Random();
    // Ensure at least one character from each selected char set
    if (length >= 1 && includeUppercase && password.length() < length) {
      password.append(UPPERCASE_CHARS.charAt(random.nextInt(UPPERCASE_CHARS.length())));
    }
    if (length >= 2 && includeLowercase && password.length() < length) {
      password.append(LOWERCASE_CHARS.charAt(random.nextInt(LOWERCASE_CHARS.length())));
    }
    if (length >= 3 && includeDigits && password.length() < length) {
      password.append(DIGIT_CHARS.charAt(random.nextInt(DIGIT_CHARS.length())));
    }
    if (length >= 4 && includeSpecial && password.length() < length) {
      password.append(SPECIAL_CHARS.charAt(random.nextInt(SPECIAL_CHARS.length())));
    }
    // Fill the rest with random characters from the selected set
    while (password.length() < length) {
      int index = random.nextInt(charSet.length());
      password.append(charSet.charAt(index));
    }
    // Shuffle the characters to avoid predictable patterns
    char[] passChars = password.toString().toCharArray();
    for (int i = passChars.length - 1; i > 0; i--) {
      int j = random.nextInt(i + 1);
      char temp = passChars[i];
      passChars[i] = passChars[j];
      passChars[j] = temp;
    }
    return new String(passChars);
  }
generateStrongPassword()
static String com.ucoruh.password.PasswordGenerator.generateStrongPassword (int length) [static]
Generates a strong password that doesn't contain weak patterns.
Keeps generating passwords until one passes the weak pattern check.
Parameters
length Desired password length
Returns
String A strong password
Definition at line 316 of file PasswordGenerator.java.
                                                          {
    String password;
    int maxAttempts = 100;
    int attempts = 0;
    do {
      password = generatePassword(length);
      attempts++;
    } while (isWeakPattern(password) && attempts < maxAttempts);
    return password;
  }
References com.ucoruh.password.PasswordGenerator.generatePassword(), and com.ucoruh.password.PasswordGenerator.isWeakPattern().
getCompressionRatio()
static double com.ucoruh.password.PasswordGenerator.getCompressionRatio (String original, String compressed) [static]
Calculates compression ratio.
Compares original size (8 bits per char) vs compressed size.
Parameters
original Original password
compressed Compressed binary string
Returns
Compression ratio (0-100%), or 0 if invalid
Definition at line 534 of file PasswordGenerator.java.
                                                                               {
    if (original == null || original.isEmpty() ||
        compressed == null || compressed.isEmpty()) {
      return 0.0;
    }
    int originalBits = original.length() * 8;
    int compressedBits = compressed.length();
    return (1.0 - ((double) compressedBits / originalBits)) * 100.0;
  }
isWeakPattern()
static boolean com.ucoruh.password.PasswordGenerator.isWeakPattern (String password) [static]
Checks if a password contains weak patterns.
Common weak patterns include: "123", "abc", "password", "qwerty", etc.
Parameters
password The password to check
Returns
boolean true if weak pattern found, false otherwise
Definition at line 260 of file PasswordGenerator.java.
                                                       {
    if (password == null || password.isEmpty()) {
      return true;
    }
    // Common weak patterns
    String[] weakPatterns = {
      "123", "1234", "12345", "123456",
      "abc", "abcd", "abcde",
      "password", "pass", "pwd",
      "qwerty", "admin", "user",
      "000", "111", "aaa",
      "password123", "admin123"
    };
    // Check case-insensitive
    String lowerPassword = password.toLowerCase();
    for (String pattern : weakPatterns) {
      if (containsPattern(lowerPassword, pattern)) {
        return true;
      }
    }
    // Check for sequential numbers (ascending)
    for (int i = 0; i < password.length() - 2; i++) {
      if (Character.isDigit(password.charAt(i)) &&
          Character.isDigit(password.charAt(i + 1)) &&
          Character.isDigit(password.charAt(i + 2))) {
        int d1 = password.charAt(i) - '0';
        int d2 = password.charAt(i + 1) - '0';
        int d3 = password.charAt(i + 2) - '0';
        if (d2 == d1 + 1 && d3 == d2 + 1) {
          return true; // Sequential like 123, 456, 789
        }
      }
    }
    // Check for repeated characters (3 or more)
    for (int i = 0; i < password.length() - 2; i++) {
      if (password.charAt(i) == password.charAt(i + 1) &&
          password.charAt(i) == password.charAt(i + 2)) {
        return true; // Repeated like aaa, 111
      }
    }
    return false;
  }
References com.ucoruh.password.PasswordGenerator.containsPattern().
Referenced by com.ucoruh.password.PasswordGenerator.generateStrongPassword().
kmpSearch()
static int com.ucoruh.password.PasswordGenerator.kmpSearch (String text, String pattern) [static]
Searches for pattern in text using KMP algorithm.
KMP (Knuth-Morris-Pratt) algorithm searches for occurrences of a pattern within a text by using the LPS array to skip unnecessary comparisons.
Time Complexity: O(n + m) where n is text length, m is pattern length Space Complexity: O(m)
Parameters
text The text to search in
pattern The pattern to search for
Returns
int Index of first occurrence, or -1 if not found
Definition at line 206 of file PasswordGenerator.java.
                                                           {
    if (text == null || pattern == null || pattern.isEmpty()) {
      return -1;
    }
    int n = text.length();
    int m = pattern.length();
    if (m > n) {
      return -1;
    }
    int[] lps = computeLPSArray(pattern);
    int i = 0; // Index for text
    int j = 0; // Index for pattern
    while (i < n) {
      if (pattern.charAt(j) == text.charAt(i)) {
        i++;
        j++;
      }
      if (j == m) {
        return i - j; // Pattern found at index i-j
      } else if (i < n && pattern.charAt(j) != text.charAt(i)) {
        if (j != 0) {
          j = lps[j - 1];
        } else {
          i++;
        }
      }
    }
    return -1; // Pattern not found
  }
Referenced by com.ucoruh.password.PasswordGenerator.containsPattern().
The documentation for this class was generated from the following file:
password-app/src/main/java/com/ucoruh/password/PasswordGenerator.java