com.ucoruh.password.AutoLoginManager Class Reference
Manages auto-login settings for password entries.
Static Public Member Functions
static boolean isAutoLoginEnabled (String service)
Checks if auto-login is enabled for a service.
static void enableAutoLogin (String service)
Enables auto-login for a service.
static void disableAutoLogin (String service)
Disables auto-login for a service.
static boolean autoLogin (String service, PasswordManager passwordManager)
Performs auto-login for a service.
static void menu (Scanner scanner, PasswordManager passwordManager)
Displays and handles the auto-login menu.
Detailed Description
Manages auto-login settings for password entries.
This class provides functionality to enable or disable auto-login for specific services and maintains a collection of services for which auto-login is enabled.
Definition at line 19 of file AutoLoginManager.java.
Member Function Documentation
autoLogin()
static boolean com.ucoruh.password.AutoLoginManager.autoLogin (String service, PasswordManager passwordManager) [static]
Performs auto-login for a service.
Attempts to automatically log in to the specified service if auto-login is enabled and credentials are available.
Parameters
service The service name to auto-login to
passwordManager The PasswordManager instance containing credentials
Returns
boolean True if auto-login was successful, false otherwise
Definition at line 118 of file AutoLoginManager.java.
                                                                                     {
        if (isAutoLoginEnabled(service)) {
            String password = passwordManager.getCredential(service);
            if (password != null) {
                System.out.println("Auto-logging in to " + service + "...");
                // Simulate login
                System.out.println("Successfully logged in to " + service);
                return true;
            }
        }
        return false;
    }
References com.ucoruh.password.PasswordManager.getCredential(), and com.ucoruh.password.AutoLoginManager.isAutoLoginEnabled().
disableAutoLogin()
static void com.ucoruh.password.AutoLoginManager.disableAutoLogin (String service) [static]
Disables auto-login for a service.
Removes the specified service from the auto-login enabled set and saves the updated settings.
Parameters
service The service name to disable auto-login for
Definition at line 103 of file AutoLoginManager.java.
                                                        {
        initialize();
        autoLoginServices.remove(service);
        saveSettings();
    }
enableAutoLogin()
static void com.ucoruh.password.AutoLoginManager.enableAutoLogin (String service) [static]
Enables auto-login for a service.
Adds the specified service to the auto-login enabled set and saves the updated settings.
Parameters
service The service name to enable auto-login for
Definition at line 90 of file AutoLoginManager.java.
                                                       {
        initialize();
        autoLoginServices.add(service);
        saveSettings();
    }
isAutoLoginEnabled()
static boolean com.ucoruh.password.AutoLoginManager.isAutoLoginEnabled (String service) [static]
Checks if auto-login is enabled for a service.
Verifies whether the specified service has auto-login enabled by checking the autoLoginServices set.
Parameters
service The service name to check
Returns
boolean True if auto-login is enabled, false otherwise
Definition at line 78 of file AutoLoginManager.java.
                                                             {
        initialize();
        return autoLoginServices.contains(service);
    }
Referenced by com.ucoruh.password.AutoLoginManager.autoLogin().
menu()
static void com.ucoruh.password.AutoLoginManager.menu (Scanner scanner, PasswordManager passwordManager) [static]
Displays and handles the auto-login menu.
Shows the auto-login management menu and processes user input for various auto-login operations.
Parameters
scanner Scanner object for reading user input
passwordManager The PasswordManager instance to use for credentials
Definition at line 139 of file AutoLoginManager.java.
                                                                              {
        initialize();
        
        boolean back = false;
        while (!back) {
            System.out.println("\n==== AUTO-LOGIN FEATURES ====");
            System.out.println("1. Enable Auto-Login for a service");
            System.out.println("2. Disable Auto-Login for a service");
            System.out.println("3. Show services with Auto-Login enabled");
            System.out.println("4. Simulate Auto-Login for a service");
            System.out.println("0. Back to Main Menu");
            System.out.print("Your choice: ");
            
            String input = scanner.nextLine();
            try {
                int choice = Integer.parseInt(input);
                switch (choice) {
                    case 1:
                        enableAutoLoginMenu(scanner, passwordManager);
                        break;
                    case 2:
                        disableAutoLoginMenu(scanner);
                        break;
                    case 3:
                        showAutoLoginServices();
                        break;
                    case 4:
                        simulateAutoLogin(scanner, passwordManager);
                        break;
                    case 0:
                        back = true;
                        break;
                    default:
                        System.out.println("Invalid choice.");
                        break;
                }
            } catch (NumberFormatException e) {
                System.out.println("Invalid number.");
            }
        }
    }
Referenced by com.ucoruh.password.PasswordApp.runApp().
The documentation for this class was generated from the following file:
password-app/src/main/java/com/ucoruh/password/AutoLoginManager.java