com.ucoruh.password.EncryptionUtil Class Reference
Utility class for encryption and decryption operations.
Static Public Member Functions
static String encrypt (String data, String masterPassword) throws Exception
Encrypts a string using AES encryption.
static String decrypt (String encryptedData, String masterPassword) throws Exception
Decrypts a string that was encrypted using AES encryption.
static String hashString (String input)
Hashes a string using SHA-256 algorithm.
Detailed Description
Utility class for encryption and decryption operations.
This class provides methods to securely encrypt and decrypt sensitive information like passwords using AES encryption with a key derived from the master password.
Definition at line 17 of file EncryptionUtil.java.
Member Function Documentation
decrypt()
static String com.ucoruh.password.EncryptionUtil.decrypt (String encryptedData, String masterPassword) throws Exception [static]
Decrypts a string that was encrypted using AES encryption.
Uses the master password to derive the decryption key and decrypts the Base64 encoded encrypted data using AES decryption.
Parameters
encryptedData The encrypted string in Base64 encoding
masterPassword The master password used to derive the decryption key
Returns
String The decrypted string
Exceptions
Exception If decryption fails
Definition at line 51 of file EncryptionUtil.java.
                                                                                               {
        SecretKeySpec secretKey = createSecretKey(masterPassword);
        Cipher cipher = Cipher.getInstance(ALGORITHM);
        cipher.init(Cipher.DECRYPT_MODE, secretKey);
        byte[] decodedData = Base64.getDecoder().decode(encryptedData);
        byte[] decryptedData = cipher.doFinal(decodedData);
        return new String(decryptedData, StandardCharsets.UTF_8);
    }
Referenced by com.ucoruh.password.DatabasePasswordStorage.readAll(), com.ucoruh.password.FilePasswordStorage.readAll(), com.ucoruh.password.DatabasePasswordStorage.update(), and com.ucoruh.password.DatabasePasswordStorage.view().
encrypt()
static String com.ucoruh.password.EncryptionUtil.encrypt (String data, String masterPassword) throws Exception [static]
Encrypts a string using AES encryption.
Uses the master password to derive an encryption key and encrypts the data using AES encryption. The result is encoded in Base64 format.
Parameters
data The string to encrypt
masterPassword The master password used to derive the encryption key
Returns
String The encrypted string in Base64 encoding
Exceptions
Exception If encryption fails
Definition at line 33 of file EncryptionUtil.java.
                                                                                      {
        SecretKeySpec secretKey = createSecretKey(masterPassword);
        Cipher cipher = Cipher.getInstance(ALGORITHM);
        cipher.init(Cipher.ENCRYPT_MODE, secretKey);
        byte[] encryptedData = cipher.doFinal(data.getBytes(StandardCharsets.UTF_8));
        return Base64.getEncoder().encodeToString(encryptedData);
    }
Referenced by com.ucoruh.password.DatabasePasswordStorage.add(), com.ucoruh.password.DatabasePasswordStorage.update(), com.ucoruh.password.DatabasePasswordStorage.writeAll(), and com.ucoruh.password.FilePasswordStorage.writeAll().
hashString()
static String com.ucoruh.password.EncryptionUtil.hashString (String input) [static]
Hashes a string using SHA-256 algorithm.
Creates a secure hash of the input string using SHA-256 algorithm and returns it in hexadecimal format. This is useful for securely storing the master password.
Parameters
input The string to hash
Returns
String The hashed string in hexadecimal format
Exceptions
RuntimeException If the SHA-256 algorithm is not available
Definition at line 93 of file EncryptionUtil.java.
                                                  {
        try {
            MessageDigest digest = MessageDigest.getInstance("SHA-256");
            byte[] hash = digest.digest(input.getBytes(StandardCharsets.UTF_8));
            StringBuilder hexString = new StringBuilder();
            for (byte b : hash) {
                String hex = Integer.toHexString(0xff & b);
                if (hex.length() == 1) hexString.append('0');
                hexString.append(hex);
            }
            return hexString.toString();
        } catch (NoSuchAlgorithmException e) {
            throw new RuntimeException("Error hashing input", e);
        }
    }
Referenced by com.ucoruh.password.AuthManager.changeMasterPassword(), com.ucoruh.password.AuthManager.createMasterPassword(), com.ucoruh.password.AuthManager.login(), and com.ucoruh.password.AuthManager.userMenu().
The documentation for this class was generated from the following file:
password-app/src/main/java/com/ucoruh/password/EncryptionUtil.java