com.ucoruh.password.FilePasswordStorage Class Reference
Implementation of InterfacePasswordStorage using file-based storage.
Classes
class XORLinkedList
XOR Linked List implementation for efficient storage audit log.
Public Member Functions
FilePasswordStorage (String masterPassword)
Constructor that initializes storage with the master password.
void add (Scanner scanner)
Adds a new password entry to the file-based storage.
void view ()
Displays all stored password entries.
void update (Scanner scanner)
Updates an existing password entry.
void delete (Scanner scanner)
Deletes a password entry from the file-based storage.
List< Password > readAll ()
Reads all password entries from the file.
void writeAll (List< Password > list)
Writes the list of password entries to the file.
void recordAudit (String operation, String service)
Records an operation in the audit log.
List< String > getAuditLog ()
Gets all audit log entries.
List< String > getRecentAuditLog (int count)
Gets recent audit log entries.
int getAuditLogSize ()
Gets audit log size.
void clearAuditLog ()
Clears audit log.
Detailed Description
Implementation of InterfacePasswordStorage using file-based storage.
Author
Password Manager Team
Version
1.0
This class provides file-based operations to store, retrieve, update, and delete password entries. All password data is encrypted using the master password.
Definition at line 16 of file FilePasswordStorage.java.
Constructor & Destructor Documentation
FilePasswordStorage()
com.ucoruh.password.FilePasswordStorage.FilePasswordStorage (String masterPassword)
Constructor that initializes storage with the master password.
Parameters
masterPassword The master password for encryption/decryption.
Definition at line 35 of file FilePasswordStorage.java.
                                                    {
    this.masterPassword = masterPassword;
  }
Member Function Documentation
add()
void com.ucoruh.password.FilePasswordStorage.add (Scanner scanner)
Adds a new password entry to the file-based storage.
This method prompts the user to enter the service, username, and password, then creates a Password object and appends its details to the passwords file.
Parameters
scanner the Scanner object used to obtain user input.
Implements com.ucoruh.password.InterfacePasswordStorage.
Definition at line 48 of file FilePasswordStorage.java.
                                   {
    System.out.print("Service: ");
    String service = scanner.nextLine();
    System.out.print("Username: ");
    String user = scanner.nextLine();
    System.out.print("Password: ");
    String pass = scanner.nextLine();
    Password p = new Password(service, user, pass);
    List<Password> passwords = readAll();
    // Check if service already exists
    boolean exists = passwords.stream()
                     .anyMatch(pwd -> pwd.getService().equalsIgnoreCase(service));
    if (exists) {
      System.out.println("A password for this service already exists. Use update option to modify it.");
      return;
    }
    passwords.add(p);
    writeAll(passwords);
    System.out.println("Password saved successfully.");
  }
References com.ucoruh.password.FilePasswordStorage.readAll(), and com.ucoruh.password.FilePasswordStorage.writeAll().
clearAuditLog()
void com.ucoruh.password.FilePasswordStorage.clearAuditLog ()
Clears audit log.
Definition at line 400 of file FilePasswordStorage.java.
                              {
    auditLog.clear();
  }
delete()
void com.ucoruh.password.FilePasswordStorage.delete (Scanner scanner)
Deletes a password entry from the file-based storage.
This method prompts the user for the service name of the entry to delete and removes the entry from the file.
Parameters
scanner the Scanner object used to obtain user input for deletion.
Implements com.ucoruh.password.InterfacePasswordStorage.
Definition at line 146 of file FilePasswordStorage.java.
                                      {
    List<Password> list = readAll();
    if (list.isEmpty()) {
      System.out.println("No records found.");
      return;
    }
    System.out.print("Service to delete: ");
    String target = scanner.nextLine();
    boolean removed = list.removeIf(p -> p.getService().equalsIgnoreCase(target));
    if (removed) {
      writeAll(list);
      System.out.println("Password deleted successfully.");
    } else {
      System.out.println("Service not found.");
    }
  }
References com.ucoruh.password.FilePasswordStorage.readAll(), and com.ucoruh.password.FilePasswordStorage.writeAll().
getAuditLog()
List< String > com.ucoruh.password.FilePasswordStorage.getAuditLog ()
Gets all audit log entries.
Returns
List of audit entries
Definition at line 374 of file FilePasswordStorage.java.
                                    {
    return auditLog.traverse();
  }
getAuditLogSize()
int com.ucoruh.password.FilePasswordStorage.getAuditLogSize ()
Gets audit log size.
Returns
Number of audit entries
Definition at line 393 of file FilePasswordStorage.java.
                               {
    return auditLog.size();
  }
getRecentAuditLog()
List< String > com.ucoruh.password.FilePasswordStorage.getRecentAuditLog (int count)
Gets recent audit log entries.
Parameters
count Number of entries
Returns
List of recent entries
Definition at line 384 of file FilePasswordStorage.java.
                                                   {
    return auditLog.getRecentEntries(count);
  }
readAll()
List< Password > com.ucoruh.password.FilePasswordStorage.readAll ()
Reads all password entries from the file.
This method opens the file and reads each line, decrypts the data, and converts it into Password objects. All valid entries are returned as a list.
Returns
a List of Password objects representing the stored password entries.
Implements com.ucoruh.password.InterfacePasswordStorage.
Definition at line 175 of file FilePasswordStorage.java.
                                  {
    List<Password> list = new ArrayList<>();
    File file = new File(FILE);
    if (!file.exists()) {
      return list;
    }
    try (BufferedReader reader = new BufferedReader(new FileReader(file))) {
      String line;
      while ((line = reader.readLine()) != null) {
        try {
          // Decrypt the line
          String decrypted = EncryptionUtil.decrypt(line, masterPassword);
          String[] parts = decrypted.split(",");
          if (parts.length == 3) {
            list.add(new Password(parts[0], parts[1], parts[2]));
          }
        } catch (Exception e) {
          // Skip lines that cannot be decrypted
          System.out.println("Warning: Could not decrypt a password entry.");
        }
      }
    } catch (IOException e) {
      System.out.println("Error reading password file: " + e.getMessage());
    }
    return list;
  }
References com.ucoruh.password.EncryptionUtil.decrypt().
Referenced by com.ucoruh.password.FilePasswordStorage.add(), com.ucoruh.password.FilePasswordStorage.delete(), com.ucoruh.password.FilePasswordStorage.update(), and com.ucoruh.password.FilePasswordStorage.view().
recordAudit()
void com.ucoruh.password.FilePasswordStorage.recordAudit (String operation, String service)
Records an operation in the audit log.
Parameters
operation Type of operation
service Service name
Definition at line 365 of file FilePasswordStorage.java.
                                                            {
    auditLog.insert(operation, service);
  }
update()
void com.ucoruh.password.FilePasswordStorage.update (Scanner scanner)
Updates an existing password entry.
This method prompts the user for the service to update and, if found, updates its username and password.
Parameters
scanner the Scanner object used to obtain user input for the update.
Implements com.ucoruh.password.InterfacePasswordStorage.
Definition at line 97 of file FilePasswordStorage.java.
                                      {
    List<Password> list = readAll();
    if (list.isEmpty()) {
      System.out.println("No records found.");
      return;
    }
    System.out.print("Service to update: ");
    String target = scanner.nextLine();
    boolean updated = false;
    for (Password p : list) {
      if (p.getService().equalsIgnoreCase(target)) {
        System.out.print("New username (leave blank to keep current '" + p.getUsername() + "'): ");
        String username = scanner.nextLine();
        if (!username.trim().isEmpty()) {
          p.setUsername(username);
        }
        System.out.print("New password (leave blank to keep current): ");
        String password = scanner.nextLine();
        if (!password.trim().isEmpty()) {
          p.setPassword(password);
        }
        updated = true;
        break;
      }
    }
    if (updated) {
      writeAll(list);
      System.out.println("Password updated successfully.");
    } else {
      System.out.println("Service not found.");
    }
  }
References com.ucoruh.password.FilePasswordStorage.readAll(), and com.ucoruh.password.FilePasswordStorage.writeAll().
view()
void com.ucoruh.password.FilePasswordStorage.view ()
Displays all stored password entries.
This method reads all password entries from the file and prints them to the console.
Implements com.ucoruh.password.InterfacePasswordStorage.
Definition at line 77 of file FilePasswordStorage.java.
                     {
    List<Password> list = readAll();
    if (list.isEmpty()) {
      System.out.println("No records found.");
    } else {
      for (int i = 0; i < list.size(); i++) {
        System.out.println((i + 1) + ". " + list.get(i));
      }
    }
  }
References com.ucoruh.password.FilePasswordStorage.readAll().
writeAll()
void com.ucoruh.password.FilePasswordStorage.writeAll (List< Password > list)
Writes the list of password entries to the file.
This method clears the existing content of the file and writes all password entries from the provided list, encrypting each entry.
Parameters
list a List of Password objects to be written to the file.
Implements com.ucoruh.password.InterfacePasswordStorage.
Definition at line 216 of file FilePasswordStorage.java.
                                            {
    try (BufferedWriter writer = new BufferedWriter(new FileWriter(FILE))) {
      for (Password p : list) {
        String data = p.getService() + "," + p.getUsername() + "," + p.getPassword();
        try {
          // Encrypt the data
          String encrypted = EncryptionUtil.encrypt(data, masterPassword);
          writer.write(encrypted);
          writer.newLine();
        } catch (Exception e) {
          System.out.println("Error encrypting password for " + p.getService() + ": " + e.getMessage());
        }
      }
    } catch (IOException e) {
      System.out.println("Error writing to password file: " + e.getMessage());
    }
  }
References com.ucoruh.password.EncryptionUtil.encrypt().
Referenced by com.ucoruh.password.FilePasswordStorage.add(), com.ucoruh.password.FilePasswordStorage.delete(), and com.ucoruh.password.FilePasswordStorage.update().
The documentation for this class was generated from the following file:
password-app/src/main/java/com/ucoruh/password/FilePasswordStorage.java